application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      Stage:
        license: Apache-2.0
        actions:
          getCustomers:
            function: actions/getCustomers/index.js
            web: "yes"
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
